# Generated by Django 5.1.5 on 2025-01-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_options_client_last_name_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Клиент')),
                ('services', models.ManyToManyField(default='', to='api.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
