# Generated by Django 5.1.5 on 2025-01-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_client_email_alter_client_first_name_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(default='', max_length=200, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.master', verbose_name='Мастер'),
        ),
    ]
