# Generated by Django 5.1.5 on 2025-01-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_client_alter_order_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.CharField(default='', max_length=40, verbose_name='Услуга'),
        ),
    ]
