# Generated by Django 5.1.5 on 2025-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_client_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='master',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена услуги'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('unpaid', 'Нет оплаты')], default='pending', max_length=20, verbose_name='Статус работы'),
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
