# Generated by Django 5.1.5 on 2025-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25, verbose_name='Цена услуги'),
        ),
    ]
