# Generated by Django 5.1.5 on 2025-02-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_client_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=25, verbose_name='Телефон'),
        ),
    ]
