# Generated by Django 5.1.5 on 2025-02-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=45, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=45, verbose_name='Цена услуги'),
        ),
        migrations.AlterField(
            model_name='client',
            name='service',
            field=models.CharField(default='', max_length=45, verbose_name='Услуга'),
        ),
    ]
