# Generated by Django 5.1.5 on 2025-02-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_client_phone_alter_client_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена услуги'),
        ),
    ]
