# Generated by Django 5.1.6 on 2025-03-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_client_phone_alter_client_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.AlterField(
            model_name='client',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена услуги'),
        ),
    ]
